version: 2

sources:
  - name: raw_data
    database: analytics
    schema: raw
    tables:
      - name: orders
        description: Raw orders data from the transactional system
        columns:
          - name: order_id
            description: Primary key of the orders table
            tests:
              - unique
              - not_null
          - name: customer_id
            description: Foreign key to the customers table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'customers')
                  field: customer_id
          - name: order_date
            description: Date when the order was placed
        loaded_at_field: updated_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        
      - name: customers
        description: Raw customer data from the transactional system
        columns:
          - name: customer_id
            description: Primary key of the customers table
            tests:
              - unique
              - not_null
          - name: email
            description: Customer email address
            tests:
              - not_null
      
      - name: products
        description: Raw product data from the inventory system
        columns:
          - name: product_id
            description: Primary key of the products table
            tests:
              - unique
              - not_null
          - name: sku
            description: Stock keeping unit - unique product identifier
            tests:
              - unique
              - not_null
          - name: category
            description: Product category
            tests:
              - not_null
              - accepted_values:
                  values: ['Electronics', 'Clothing', 'Home', 'Office', 'Sports', 'Food', 'Other']
        loaded_at_field: updated_at
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
          
      - name: order_items
        description: Raw order items data linking orders and products
        columns:
          - name: order_item_id
            description: Primary key of the order items table
            tests:
              - unique
              - not_null
          - name: order_id
            description: Foreign key to the orders table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'orders')
                  field: order_id
          - name: product_id
            description: Foreign key to the products table
            tests:
              - not_null
              - relationships:
                  to: source('raw_data', 'products')
                  field: product_id