version: 2

models:
  - name: dim_customers
    description: "Customer dimension table"
    columns:
      - name: customer_id
        description: "Primary key of the customers dimension"
        tests:
          - unique
          - not_null
      - name: full_name
        description: "Customer's full name"
      - name: region
        description: "Geographic region the customer belongs to"
        tests:
          - accepted_values:
              values: ['West', 'East', 'South', 'Other']

  - name: dim_products
    description: "Product dimension table"
    columns:
      - name: product_id
        description: "Primary key of the products dimension"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Name of the product"
        tests:
          - not_null
      - name: category
        description: "Product category"
      - name: price_tier
        description: "Price category (Budget, Regular, Premium)"
        tests:
          - accepted_values:
              values: ['Budget', 'Regular', 'Premium']

  - name: fct_orders
    description: "Order fact table"
    columns:
      - name: order_id
        description: "Primary key of the orders fact table"
        tests:
          - unique
          - not_null
      - name: customer_id
        description: "Foreign key to the customer dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_customers')
              field: customer_id
      - name: amount
        description: "Total amount of the order"
        tests:
          - not_null

  - name: fct_order_items
    description: "Order items fact table"
    columns:
      - name: order_item_id
        description: "Primary key of the order items fact table"
        tests:
          - unique
          - not_null
      - name: order_id
        description: "Foreign key to the orders fact table"
        tests:
          - not_null
          - relationships:
              to: ref('fct_orders')
              field: order_id
      - name: product_id
        description: "Foreign key to the products dimension"
        tests:
          - not_null
          - relationships:
              to: ref('dim_products')
              field: product_id
      - name: line_total
        description: "Total amount for the line item"
        tests:
          - not_null

  - name: customer_orders
    description: "Aggregated customer metrics"
    columns:
      - name: customer_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: order_count
        description: "Number of orders placed by the customer"
        tests:
          - not_null
      - name: total_amount
        description: "Total amount spent by the customer"
      - name: customer_segment
        description: "Customer segment categorization"
        
  - name: product_performance
    description: "Aggregated product performance metrics"
    columns:
      - name: product_id
        description: "Primary key"
        tests:
          - unique
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the product"
      - name: total_profit
        description: "Total profit generated by the product"
      - name: product_status
        description: "Current status of the product (Active, Slowing, Inactive)"
        tests:
          - accepted_values:
              values: ['Active', 'Slowing', 'Inactive']