name: dbt CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    env:
      REDSHIFT_HOST: ${{ secrets.REDSHIFT_HOST }}
      REDSHIFT_USER: ${{ secrets.REDSHIFT_USER }}
      REDSHIFT_PASSWORD: ${{ secrets.REDSHIFT_PASSWORD }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-redshift
        dbt deps
      
    - name: Check sources
      run: dbt source freshness
      
    - name: Lint SQL
      run: |
        pip install sqlfluff
        sqlfluff lint models/
      
    - name: Run dbt tests
      run: dbt test
      
    - name: Generate documentation
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: dbt docs generate
      
    - name: Deploy to dev
      if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
      run: |
        dbt run --target dev
        
    - name: Deploy to production
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: |
        dbt run --target prod